Models/NovedadesItem/NovedadesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InventarioLPS.Models.NovedadesItem
{
    public class NovedadesViewModel
    {
        public int IdItemInventario { get; set; }

        // CAMPOS PARA `_ResumenNovedadesPartial.cshtml`
        public string? CodigoItem { get; set; }

        public string? NombreProducto { get; set; }

        public string? DescripcionEspecifica { get; set; }

        public string? EspecificacionesTecnicas { get; set; }

        public string? FormaRegistro { get; set; }

        public string? NumeroDocumento { get; set; }

        public DateTime? FechaCompra { get; set; }

        public List<DetallesNovedadItemViewModel>? Detalles { get; set; }

        // CAMPOS EXTRA PARA Create.cshtml
        [Required(ErrorMessage = "*Campo requerido.")]
        [DataType(DataType.Date)]
        public DateTime FechaNuevaNovedad { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "*Campo requerido.")]
        public string NuevaNovedad { get; set; }

    }
}

Controllers/InventarioController.cs
using System.Text.Json;
using InventarioLPS.Data;
using InventarioLPS.Data.Entities;
using InventarioLPS.Models.Inventario;
using InventarioLPS.Services.Mappings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace InventarioLPS.Controllers
{
    public class InventarioController : BaseController
    {
        private readonly InventarioLPSContext _context;

        public InventarioController(InventarioLPSContext context)
        {
            _context = context;

        }
        // GET: InventarioController
        public async Task<IActionResult> Index()
        {
            try
            {
                List<ItemInventario> inventario = await _context.ItemInventario
                                .Include(i => i.IdInformacionRegistroNavigation.IdFormaRegistroNavigation)
                                .Include(i => i.CodigoProductoNavigation)
                                .ToListAsync();

                var model = InventarioMapping.ToInventarioViewModelList(inventario);

                return View(model);
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }

        // GET: Inventario/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                var model = await BuildCreateRegistroViewModelAsync();
                return View(model);
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }


        // POST: InventarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRegistroInventarioViewModel model)
        {
            try
            {
                RemoveNonValidateFieldsCreation(model);
                if (!ModelState.IsValid)
                {
                    CreateRegistroInventarioViewModel modelInvalid = await BuildCreateRegistroViewModelAsync();
                    modelInvalid.Items = model.Items;
                    ModelState.AddModelError("", "Existen campos no válidos.");
                    return View(modelInvalid);
                }

                List<string> codigosItem = model.Items
                    .Select(i => i.CodigoItem)
                    .ToList();

                List<string> existingCodigosItem = await _context.ItemInventario
                    .Where(i => codigosItem.Contains(i.CodigoItem))
                    .Select(i => i.CodigoItem)
                    .ToListAsync();

                if (existingCodigosItem.Any())
                {
                    CreateRegistroInventarioViewModel modelInvalid = await BuildCreateRegistroViewModelAsync();
                    modelInvalid.Items = model.Items;
                    for (int i = 0; i < model.Items.Count; i++)
                    {
                        var codigo = model.Items[i].CodigoItem;
                        if (existingCodigosItem.Contains(codigo))
                        {
                            ModelState.AddModelError($"Items[{i}].CodigoItem", $"Código ya existente.");
                        }
                    }
                    return View(modelInvalid);
                }

                InformacionRegistro newDataRegister = InventarioMapping.ToInformacionRegisterEntity(model);
                await _context.InformacionRegistro.AddAsync(newDataRegister);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }
        private void RemoveNonValidateFieldsCreation(CreateRegistroInventarioViewModel model)
        {
            for (int i = 0; i < model.Items.Count; i++)
            {
                ModelState.Remove($"Items[{i}].Producto");
                ModelState.Remove($"Items[{i}].FormaRegistro");
                ModelState.Remove($"Items[{i}].NumeroDocumento");
                ModelState.Remove($"Items[{i}].FechaCompra");
            }
        }


        // GET: InventarioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InventarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // POST: NovedadesItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.ItemInventario.FindAsync(id);
            if (item != null)
            {
                _context.ItemInventario.Remove(item);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<CreateRegistroInventarioViewModel> BuildCreateRegistroViewModelAsync()
        {
            var formasRegistro = await _context.FormaRegistro.ToListAsync();
            var proveedores = await _context.Proveedor.ToListAsync();
            var productos = await _context.Producto.ToListAsync();
            var ubicaciones = await _context.Ubicacion.ToListAsync();
            var estatus = await _context.Estatus.ToListAsync();
            var clasificaciones = await _context.Clasificacion.ToListAsync();

            var productoInfo = await _context.Producto
                .Include(p => p.IdDepartamentoNavigation)
                .Include(p => p.IdCategoriaNavigation)
                .Include(p => p.IdLineaServicioNavigation)
                .Include(p => p.IdSubLineaServicioNavigation)
                .Select(p => new
                {
                    p.Codigo,
                    Departamento = p.IdDepartamentoNavigation.Nombre,
                    Categoria = p.IdCategoriaNavigation.Nombre,
                    LineaServicio = p.IdLineaServicioNavigation.Nombre,
                    SubLineaServicio = p.IdSubLineaServicioNavigation.Nombre
                    //SubLineaServicio = p.IdSubLineaServicioNavigation != null
                    //                   ? p.IdSubLineaServicioNavigation.Nombre
                    //                   : ""
                })
                .ToListAsync();

            return new CreateRegistroInventarioViewModel
            {
                FormasRegistroOptions = new SelectList(formasRegistro, "Id", "Nombre"),
                ProveedoresOptions = new SelectList(proveedores, "NombreComercial", "NombreComercial"),
                ProductosOptions = new SelectList(productos, "Codigo", "Nombre"),
                UbicacionesOptions = new SelectList(ubicaciones, "Nombre", "Nombre"),
                EstatusOptions = new SelectList(estatus, "Nombre", "Nombre"),
                ClasificacionesOptions = new SelectList(clasificaciones, "Nombre", "Nombre"),
                ProductInfoJson = JsonSerializer.Serialize(
                    productoInfo.ToDictionary(x => x.Codigo, x => new
                    {
                        x.Departamento,
                        x.Categoria,
                        x.LineaServicio,
                        x.SubLineaServicio
                    }),
                    new JsonSerializerOptions()
                )
            };
        }
    }
}

Controllers/NovedadesController.cs
using InventarioLPS.Data;
using InventarioLPS.Data.Entities;
using InventarioLPS.Models.NovedadesItem;
using InventarioLPS.Services.Mappings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventarioLPS.Controllers
{
    public class NovedadesController : BaseController
    {
        private readonly InventarioLPSContext _context;

        public NovedadesController(InventarioLPSContext context)
        {
            _context = context;

        }
        // GET: Novedades/Create/
        public async Task<IActionResult> Create(int idItem)
        {
            NovedadesViewModel model = await GetNovedadesByItemId(idItem);
            return View(model);
        }

        // POST: Novedades/Create/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NovedadesViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Existen campos no válidos.");
                return View(model);
            }
            try
            {
                NovedadItem newNovedad = NovedadesMapping.ToNovedadItem(model);
                // tod hacer algo con la persistencia de datos. de iteminvenatrio.
                await _context.NovedadItem.AddAsync(newNovedad);
                await _context.SaveChangesAsync();
                // Redirigir a la vista de detalles de la novedad
                return RedirectToAction(nameof(Details), new { idItem = model.IdItemInventario });
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }


        // GET: Novedades/Details/5
        public async Task<IActionResult> Details(int idItem)
        {
            NovedadesViewModel model = await GetNovedadesByItemId(idItem);
            return View(model);
        }

        private async Task<NovedadesViewModel> GetNovedadesByItemId(int idItem)
        {
            ItemInventario itemInvetario = await _context.ItemInventario
               .Include(i => i.CodigoProductoNavigation)
               .Include(i => i.IdInformacionRegistroNavigation.IdFormaRegistroNavigation)
               .Include(i => i.IdInformacionRegistroNavigation)
               .FirstAsync(i => i.Id == idItem);
            List<NovedadItem> novedadesItem = await _context.NovedadItem
                .Where(i => i.IdItemInventario == idItem)
                .ToListAsync();
            return NovedadesMapping.ToNovedadesItemViewModel(itemInvetario, novedadesItem);
        }

        // POST: NovedadesItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var novedadItem = await _context.NovedadItem.FindAsync(id);
            if (novedadItem != null)
            {
                _context.NovedadItem.Remove(novedadItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Create), new { id });
        }
    }
}

Views/Novedades/Create.cshtml
@model NovedadesViewModel

@{
    ViewData["Title"] = "Agregar detalle a item";
}
<h4>@ViewBag.Title</h4>
<hr />
<form asp-action="Create" >
    <div class="row">
		<div class="col">
			<button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        <div class="col">
            <a asp-action="Index" asp-controller="Inventario" class="btn btn-primary"><i class="bi bi-arrow-left-square"></i> Regresar</a>
        </div>
    </div>
	<div class="row">
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="col-5 col-md-3">
			<label asp-for="FechaNuevaNovedad" class="form-label">Fecha</label>
			<input asp-for="FechaNuevaNovedad" class="form-control" />
			<span asp-validation-for="FechaNuevaNovedad" class="text-danger"></span>
		</div>
		<div class="col-5">
			<label asp-for="NuevaNovedad" class="form-label">Nueva novedad</label>
			<textarea asp-for="NuevaNovedad" class="form-control" placeholder="Ingresar nueva novedad"></textarea>
			<span asp-validation-for="NuevaNovedad" class="text-danger"></span>
		</div>
    </div>

	<hr />
	<div class="row">
		@await Html.PartialAsync("_ResumenNovedadesPartial.cshtml", Model)
	</div>
</form>

Views/Novedades/Details.cshtml
@model NovedadesViewModel

@{
    ViewData["Title"] = "Detalle de novedades de inventario";
}
<h4>@ViewBag.Title</h4>
<hr />
<div class="row">
    <div class="col">
        <a asp-action="Create" asp-route-idItem="@Model.IdItemInventario" class="btn btn-secondary bg-primary-site"><i class="bi bi-plus"></i>Nuevo</a>
    </div>
    <div class="col">
        <a asp-action="Index" asp-controller="Inventario" class="btn btn-primary"><i class="bi bi-arrow-left-square"></i> Regresar</a>
    </div>
</div>
@await Html.PartialAsync("_ResumenNovedadesPartial.cshtml", Model)

Views/Novedades/_ResumenNovedadesPartial.cshtml
@model NovedadesViewModel

<h4 class="mx-auto">Información de item de Inventario</h4>
<dl class="row">
	<div class="col-7 col-lg-4">
		<dt>Codigo de Item</dt>
		<dd>@Model.CodigoItem</dd>
	</div>
	<div class="col-7 col-lg-4">
		<dt>Producto</dt>
		<dd>@Model.NombreProducto</dd>
	</div>
	<div class="col-7 col-lg-4">
		<dt>Descripción Específica</dt>
		<dd>@Model.DescripcionEspecifica</dd>
	</div>
	<div class="col-7 col-lg-4">
		<dt>Especificaciones Técnicas</dt>
		<dd>@Model.EspecificacionesTecnicas</dd>
	</div>
	<div class="col-7 col-lg-4">
		<dt>Forma de Registro</dt>
		<dd>@Model.FormaRegistro</dd>
	</div>
	<div class="col-7 col-lg-4">
		<dt># de Documento</dt>
		<dd>@Model.NumeroDocumento</dd>
	</div>
</dl>

<hr />

<h4>Detalle de Novedades</h4>

<div class="table-responsive">
	<table class="table">
		<thead>
			<tr>
				<th>Fecha</th>
				<th>Fecha</th>
				<th>Novedad</th>
			</tr>
		</thead>
		<tbody>
			@if (Model.Detalles?.Any() == true)
			{
				@foreach (var item in Model.Detalles)
				{
					<tr>
						<td>
							<a asp-action="Edit" asp-route-id="@item.Id" data-bs-toggle="tooltip" data-bs-title="Editar" class="border btn btn-light btn-sm px-2 py-1">
								<i class="bi bi-pencil-square"></i>
							</a>
							<button type="button"
									data-bs-toggle="modal"
									data-bs-target="#genericConfirmModal"
									data-action="/Novedades/Delete/@item.Id"
									data-body="¿Desea eliminar la novedad?<br><strong>Fecha:</strong> @item.Fecha.ToString("yyyy-MM-dd")<br><strong>Novedad:</strong> @item.Novedad"
									title="Eliminar"
									class="btn btn-danger btn-sm px-2 py-1 my-1">
								<i class="bi bi-trash"></i>
							</button>

						</td>
						<td>@item.Fecha.ToString("yyyy-MM-dd")</td>
						<td>@item.Novedad</td>
					</tr>
				}
			}
			else
			{
				<tr>
					<td colspan="2">
						<div class="text-center text-muted small">
							No existen detalles por el momento.
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>