Models/Inventario/CreateRegistroInventarioViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InventarioLPS.Models.Inventario
{
    public class CreateRegistroInventarioViewModel
    {
        // CAMPOS DEL DOCUMENTO.
        [Required(ErrorMessage = "*Campo requerido.")]
        public int FormaRegistroId { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string NumeroDocumento { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        [DataType(DataType.Date)]
        public DateTime FechaCompra { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "*Campo requerido.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El monto debe ser mayor a 0.")]
        public decimal MontoTotal { get; set; }


        // ITEMS.
        public List<ItemInventarioViewModel> Items { get; set; } = new();


        // LISTAS PARA LOS SELECTS.
        public IEnumerable<SelectListItem>? FormasRegistroOptions { get; set; }
        public IEnumerable<SelectListItem>? ProveedoresOptions { get; set; }
        public IEnumerable<SelectListItem>? ProductosOptions { get; set; }
        public IEnumerable<SelectListItem>? UbicacionesOptions { get; set; }
        public IEnumerable<SelectListItem>? EstatusOptions { get; set; }
        public IEnumerable<SelectListItem>? ClasificacionesOptions { get; set; }

        // JSON CON INFO DEL PRODUCTO PARA EL SCRIPT.
        public string? ProductInfoJson { get; set; }

    }
}

Models/Inventario/ItemInventarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InventarioLPS.Models.Inventario
{
    public class ItemInventarioViewModel
    {
        // CAMPOS PARA Index.cshtml
        public int Id { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string CodigoItem { get; set; }

        public string FormaRegistro { get; set; }

        public string NumeroDocumento { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaCompra { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El valor debe ser mayor a 0.")]
        public decimal ValorUnitarioSinIva { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "La cantidad debe ser al menos 1.")]
        public int Cantidad { get; set; }

        public decimal TotalSinIva { get; set; }

        public string Producto { get; set; }

        public string Departamento { get; set; }

        public string Categoria { get; set; }

        public string LineaServicio { get; set; }

        public string? SubLineaServicio { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string DescripcionEspecifica { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string EspecificacionesTecnicas { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string NumeroParteFabricante { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string NumeroSerieLps { get; set; }


        [Required(ErrorMessage = "*Campo requerido.")]
        public string Estatus { get; set; }


        [Required(ErrorMessage = "*Campo requerido.")]
        public string Ubicacion { get; set; }


        [Required(ErrorMessage = "*Campo requerido.")]
        public string Clasificacion { get; set; }

        [Required(ErrorMessage = "*Campo requerido.")]
        public string Proveedor { get; set; }



        // CAMPOS PARA Create.cshtml

        [Required(ErrorMessage = "*Campo requerido.")]
        public string CodigoProducto { get; set; }
    }
}

Controllers/InventarioController.cs
using System.Text.Json;
using InventarioLPS.Data;
using InventarioLPS.Data.Entities;
using InventarioLPS.Models.Inventario;
using InventarioLPS.Services.Mappings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace InventarioLPS.Controllers
{
    public class InventarioController : BaseController
    {
        private readonly InventarioLPSContext _context;

        public InventarioController(InventarioLPSContext context)
        {
            _context = context;

        }
        // GET: InventarioController
        public async Task<IActionResult> Index()
        {
            try
            {
                List<ItemInventario> inventario = await _context.ItemInventario
                                .Include(i => i.IdInformacionRegistroNavigation.IdFormaRegistroNavigation)
                                .Include(i => i.CodigoProductoNavigation)
                                .ToListAsync();

                var model = InventarioMapping.ToInventarioViewModelList(inventario);

                return View(model);
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }

        // GET: Inventario/Create
        public async Task<IActionResult> Create()
        {
            try
            {
                var model = await BuildCreateRegistroViewModelAsync();
                return View(model);
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }


        // POST: InventarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRegistroInventarioViewModel model)
        {
            try
            {
                RemoveNonValidateFieldsCreation(model);
                if (!ModelState.IsValid)
                {
                    CreateRegistroInventarioViewModel modelInvalid = await BuildCreateRegistroViewModelAsync();
                    modelInvalid.Items = model.Items;
                    ModelState.AddModelError("", "Existen campos no válidos.");
                    return View(modelInvalid);
                }

                List<string> codigosItem = model.Items
                    .Select(i => i.CodigoItem)
                    .ToList();

                List<string> existingCodigosItem = await _context.ItemInventario
                    .Where(i => codigosItem.Contains(i.CodigoItem))
                    .Select(i => i.CodigoItem)
                    .ToListAsync();

                if (existingCodigosItem.Any())
                {
                    CreateRegistroInventarioViewModel modelInvalid = await BuildCreateRegistroViewModelAsync();
                    modelInvalid.Items = model.Items;
                    for (int i = 0; i < model.Items.Count; i++)
                    {
                        var codigo = model.Items[i].CodigoItem;
                        if (existingCodigosItem.Contains(codigo))
                        {
                            ModelState.AddModelError($"Items[{i}].CodigoItem", $"Código ya existente.");
                        }
                    }
                    return View(modelInvalid);
                }

                InformacionRegistro newDataRegister = InventarioMapping.ToInformacionRegisterEntity(model);
                await _context.InformacionRegistro.AddAsync(newDataRegister);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }
        private void RemoveNonValidateFieldsCreation(CreateRegistroInventarioViewModel model)
        {
            for (int i = 0; i < model.Items.Count; i++)
            {
                ModelState.Remove($"Items[{i}].Producto");
                ModelState.Remove($"Items[{i}].FormaRegistro");
                ModelState.Remove($"Items[{i}].NumeroDocumento");
                ModelState.Remove($"Items[{i}].FechaCompra");
            }
        }


        // GET: InventarioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InventarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // POST: NovedadesItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.ItemInventario.FindAsync(id);
            if (item != null)
            {
                _context.ItemInventario.Remove(item);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private async Task<CreateRegistroInventarioViewModel> BuildCreateRegistroViewModelAsync()
        {
            var formasRegistro = await _context.FormaRegistro.ToListAsync();
            var proveedores = await _context.Proveedor.ToListAsync();
            var productos = await _context.Producto.ToListAsync();
            var ubicaciones = await _context.Ubicacion.ToListAsync();
            var estatus = await _context.Estatus.ToListAsync();
            var clasificaciones = await _context.Clasificacion.ToListAsync();

            var productoInfo = await _context.Producto
                .Include(p => p.IdDepartamentoNavigation)
                .Include(p => p.IdCategoriaNavigation)
                .Include(p => p.IdLineaServicioNavigation)
                .Include(p => p.IdSubLineaServicioNavigation)
                .Select(p => new
                {
                    p.Codigo,
                    Departamento = p.IdDepartamentoNavigation.Nombre,
                    Categoria = p.IdCategoriaNavigation.Nombre,
                    LineaServicio = p.IdLineaServicioNavigation.Nombre,
                    SubLineaServicio = p.IdSubLineaServicioNavigation.Nombre
                    //SubLineaServicio = p.IdSubLineaServicioNavigation != null
                    //                   ? p.IdSubLineaServicioNavigation.Nombre
                    //                   : ""
                })
                .ToListAsync();

            return new CreateRegistroInventarioViewModel
            {
                FormasRegistroOptions = new SelectList(formasRegistro, "Id", "Nombre"),
                ProveedoresOptions = new SelectList(proveedores, "NombreComercial", "NombreComercial"),
                ProductosOptions = new SelectList(productos, "Codigo", "Nombre"),
                UbicacionesOptions = new SelectList(ubicaciones, "Nombre", "Nombre"),
                EstatusOptions = new SelectList(estatus, "Nombre", "Nombre"),
                ClasificacionesOptions = new SelectList(clasificaciones, "Nombre", "Nombre"),
                ProductInfoJson = JsonSerializer.Serialize(
                    productoInfo.ToDictionary(x => x.Codigo, x => new
                    {
                        x.Departamento,
                        x.Categoria,
                        x.LineaServicio,
                        x.SubLineaServicio
                    }),
                    new JsonSerializerOptions()
                )
            };
        }
    }
}

Controllers/NovedadesController.cs
using InventarioLPS.Data;
using InventarioLPS.Data.Entities;
using InventarioLPS.Models.NovedadesItem;
using InventarioLPS.Services.Mappings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InventarioLPS.Controllers
{
    public class NovedadesController : BaseController
    {
        private readonly InventarioLPSContext _context;

        public NovedadesController(InventarioLPSContext context)
        {
            _context = context;

        }
        // GET: Novedades/Create/
        public async Task<IActionResult> Create(int idItem)
        {
            NovedadesViewModel model = await GetNovedadesByItemId(idItem);
            return View(model);
        }

        // POST: Novedades/Create/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(NovedadesViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Existen campos no válidos.");
                return View(model);
            }
            try
            {
                NovedadItem newNovedad = NovedadesMapping.ToNovedadItem(model);
                // tod hacer algo con la persistencia de datos. de iteminvenatrio.
                await _context.NovedadItem.AddAsync(newNovedad);
                await _context.SaveChangesAsync();
                // Redirigir a la vista de detalles de la novedad
                return RedirectToAction(nameof(Details), new { idItem = model.IdItemInventario });
            }
            catch (Exception ex)
            {
                return ShowErrorPageFromException(ex);
            }
        }


        // GET: Novedades/Details/5
        public async Task<IActionResult> Details(int idItem)
        {
            NovedadesViewModel model = await GetNovedadesByItemId(idItem);
            return View(model);
        }

        private async Task<NovedadesViewModel> GetNovedadesByItemId(int idItem)
        {
            ItemInventario itemInvetario = await _context.ItemInventario
               .Include(i => i.CodigoProductoNavigation)
               .Include(i => i.IdInformacionRegistroNavigation.IdFormaRegistroNavigation)
               .Include(i => i.IdInformacionRegistroNavigation)
               .FirstAsync(i => i.Id == idItem);
            List<NovedadItem> novedadesItem = await _context.NovedadItem
                .Where(i => i.IdItemInventario == idItem)
                .ToListAsync();
            return NovedadesMapping.ToNovedadesItemViewModel(itemInvetario, novedadesItem);
        }

        // POST: NovedadesItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var novedadItem = await _context.NovedadItem.FindAsync(id);
            if (novedadItem != null)
            {
                _context.NovedadItem.Remove(novedadItem);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Create), new { id });
        }
    }
}

Views/Inventario/Index.cshtml
@model IEnumerable<ItemInventarioViewModel>

@{
	ViewData["Title"] = "Inventario";
}
<h2>@ViewBag.Title</h2>
<div class="row">
	<div class="col">
		<a asp-action="Create" class="btn btn-secondary bg-primary-site"><i class="bi bi-plus"></i>Nuevo</a>
	</div>
</div>

<div class="table-responsive ">
	<table class="table">
		<thead class="fs-theader">
			<tr>
				<th>Opciones</th>
				<th>Código</th>
				<th>Forma registro</th>
				<th># Documento</th>
				<th>Fecha de compra</th>
				<th>Valor Unit. sin IVA</th>
				<th>Cantidad</th>
				<th>Total sin IVA</th>
				<th>Producto</th>
				<th>Departamento</th>
				<th>Categoría</th>
				<th>Línea de servicio</th>
				<th>Sub-línea</th>
				<th>Descrip. específica</th>
				<th>Especifi. técnicas</th>
				<th># fabricante</th>
				<th># serie LPS</th>
				<th>Estatus</th>
				<th>Ubicación</th>
				<th>Clasificación</th>
				<th>Proveedor</th>
			</tr>
		</thead>
		<tbody class="fs-tbody">
			@foreach (var item in Model)
			{
				<tr>
					<td class="ps-4 pe-5">
						<a asp-action="Edit" asp-route-id="@item.Id" data-bs-toggle="tooltip" data-bs-title="Editar" class=" border btn btn-light btn-sm px-2 py-1">
							<i class="bi bi-pencil-square"></i>
						</a>
						<button type="button"
								data-bs-toggle="modal"
								data-bs-target="#genericConfirmModal"
								data-action="/Inventario/Delete/@item.Id"
								data-body="¿Desea eliminar este item? Se eliminaran sus novedades registradas en caso de existir.<br><strong>Código:</strong> @item.CodigoItem<br><strong>Producto:</strong> @item.Producto<br><strong>Desc. Específica:</strong> @item.DescripcionEspecifica"
								title="Eliminar"
								class="btn btn-danger btn-sm px-2 py-1 my-1">
							<i class="bi bi-trash"></i>
						</button>
						<a asp-controller="Novedades" asp-action="Create" asp-route-idItem="@item.Id" data-bs-toggle="tooltip" data-bs-title="Agregar novedades" class=" border btn btn-light btn-sm px-2 py-1">
							<i class="bi bi-clipboard-plus"></i>
						</a>
						<a asp-controller="Novedades" asp-action="Details" asp-route-idItem="@item.Id" data-bs-toggle="tooltip" data-bs-title="Ver novedades" class=" border btn btn-light btn-sm px-2 py-1">
							<i class="bi bi-card-list"></i>
						</a>
					</td>
					<td class="fs-td td-codigo">@item.CodigoItem</td>
					<td class="fs-td td-formaRegistro">@item.FormaRegistro</td>
					<td class="fs-td td-numDoc">@item.NumeroDocumento</td>
					<td class="fs-td td-fechaCompra">@item.FechaCompra.ToString("yyyy-MM-dd")</td>
					<td class="fs-td td-valor">@item.ValorUnitarioSinIva.ToString("0.################").TrimEnd('0').TrimEnd('.')</td>
					<td class="fs-td td-cantidad">@item.Cantidad</td>
					<td class="fs-td td-valor">@item.TotalSinIva.ToString("0.################").TrimEnd('0').TrimEnd('.')</td>
					<td class="fs-td td-producto">@item.Producto</td>
					<td class="fs-td td-departamento">@item.Departamento</td>
					<td class="fs-td td-categoria">@item.Categoria</td>
					<td class="fs-td td-linea">@item.LineaServicio</td>
					<td class="fs-td td-sublinea">@item.SubLineaServicio</td>
					<td class="fs-td td-descripcion">@item.DescripcionEspecifica</td>
					<td class="fs-td td-especificaciones">@item.EspecificacionesTecnicas</td>
					<td class="fs-td td-parte">@item.NumeroParteFabricante</td>
					<td class="fs-td td-serie">@item.NumeroSerieLps</td>
					<td class="fs-td td-estatus">@item.Estatus</td>
					<td class="fs-td td-ubicacion">@item.Ubicacion</td>
					<td class="fs-td td-clasificacion">@item.Clasificacion</td>
					<td class="fs-td td-proveedor">@item.Proveedor</td>
				</tr>
			}
		</tbody>
	</table>
</div>